### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scottmconway** [koro666/notifikator#4]
Perhaps it's a bit late to ask, but I've forked this repository and intend to add a few features to it (and perhaps even maintain it).
https://github.com/scottmconway/notifikator/

Could you add a license to this repo, so I can be sure of how it can be used? As of now it just falls under your personal copyright.

**Comment by koro666** [comment]
Sorry, haven't touched this in a while, lots of other side-projects taking my time.

I have not thought of a specific license, but the gist of it would be "do whatever you want with it, as long as it's non-commercial".

That said, if you deviate significantly from the original repository, please change the application ID to something else so there's no confusion.

**Comment by scottmconway** [comment]
Got it, thanks! That basically sounds like a Creative Commons Non-Commercial license.
